# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from quivr_python_sdk.pydantic.chat_item_type import ChatItemType
from quivr_python_sdk.pydantic.get_chat_history_output import GetChatHistoryOutput
from quivr_python_sdk.pydantic.notification import Notification

class ChatItem(BaseModel):
    item_type: ChatItemType = Field(alias='item_type')

    body: typing.Union[GetChatHistoryOutput, Notification] = Field(alias='body')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
