# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ChatQuestion(BaseModel):
    question: str = Field(alias='question')

    model: typing.Optional[typing.Optional[str]] = Field(None, alias='model')

    temperature: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='temperature')

    max_tokens: typing.Optional[typing.Optional[int]] = Field(None, alias='max_tokens')

    brain_id: typing.Optional[typing.Optional[str]] = Field(None, alias='brain_id')

    prompt_id: typing.Optional[typing.Optional[str]] = Field(None, alias='prompt_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
