# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class CrawlWebsite(BaseModel):
    url: str = Field(alias='url')

    js: typing.Optional[bool] = Field(None, alias='js')

    depth: typing.Optional[int] = Field(None, alias='depth')

    max_pages: typing.Optional[int] = Field(None, alias='max_pages')

    max_time: typing.Optional[int] = Field(None, alias='max_time')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
