# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from quivr_python_sdk.pydantic.brain_integration_settings_nullable import BrainIntegrationSettingsNullable
from quivr_python_sdk.pydantic.brain_type_nullable import BrainTypeNullable
from quivr_python_sdk.pydantic.create_api_brain_definition_nullable import CreateApiBrainDefinitionNullable
from quivr_python_sdk.pydantic.create_brain_properties_connected_brains_ids import CreateBrainPropertiesConnectedBrainsIds

class CreateBrainProperties(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    name: typing.Optional[typing.Optional[str]] = Field(None, alias='name')

    status: typing.Optional[typing.Optional[str]] = Field(None, alias='status')

    model: typing.Optional[typing.Optional[str]] = Field(None, alias='model')

    temperature: typing.Optional[typing.Optional[typing.Union[int, float]]] = Field(None, alias='temperature')

    max_tokens: typing.Optional[typing.Optional[int]] = Field(None, alias='max_tokens')

    prompt_id: typing.Optional[typing.Optional[str]] = Field(None, alias='prompt_id')

    brain_type: typing.Optional[BrainTypeNullable] = Field(None, alias='brain_type')

    brain_definition: typing.Optional[CreateApiBrainDefinitionNullable] = Field(None, alias='brain_definition')

    brain_secrets_values: typing.Optional[typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]] = Field(None, alias='brain_secrets_values')

    connected_brains_ids: typing.Optional[CreateBrainPropertiesConnectedBrainsIds] = Field(None, alias='connected_brains_ids')

    integration: typing.Optional[BrainIntegrationSettingsNullable] = Field(None, alias='integration')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
