# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from quivr_python_sdk.pydantic.integration_brain_tag import IntegrationBrainTag
from quivr_python_sdk.pydantic.integration_type import IntegrationType

class IntegrationDescriptionEntity(BaseModel):
    description: str = Field(alias='description')

    id: str = Field(alias='id')

    integration_name: str = Field(alias='integration_name')

    integration_type: IntegrationType = Field(alias='integration_type')

    max_files: int = Field(alias='max_files')

    allow_model_change: bool = Field(alias='allow_model_change')

    integration_display_name: str = Field(alias='integration_display_name')

    tags: typing.Optional[typing.Optional[typing.List[IntegrationBrainTag]]] = Field(None, alias='tags')

    integration_logo_url: typing.Optional[typing.Optional[str]] = Field(None, alias='integration_logo_url')

    connection_settings: typing.Optional[typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]] = Field(None, alias='connection_settings')

    information: typing.Optional[typing.Optional[str]] = Field(None, alias='information')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
