# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from quivr_python_sdk.pydantic.notifications_status_enum import NotificationsStatusEnum

class Notification(BaseModel):
    id: str = Field(alias='id')

    datetime: str = Field(alias='datetime')

    action: str = Field(alias='action')

    status: NotificationsStatusEnum = Field(alias='status')

    chat_id: typing.Optional[typing.Optional[str]] = Field(None, alias='chat_id')

    message: typing.Optional[typing.Optional[str]] = Field(None, alias='message')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
