# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class OnboardingStatesNullable(BaseModel):
    onboarding_a: bool = Field(alias='onboarding_a')

    onboarding_b1: bool = Field(alias='onboarding_b1')

    onboarding_b2: bool = Field(alias='onboarding_b2')

    onboarding_b3: bool = Field(alias='onboarding_b3')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
