# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from quivr_python_sdk.pydantic.prompt_status_enum_nullable import PromptStatusEnumNullable

class PromptUpdatableProperties(BaseModel):
    title: typing.Optional[typing.Optional[str]] = Field(None, alias='title')

    content: typing.Optional[typing.Optional[str]] = Field(None, alias='content')

    status: typing.Optional[PromptStatusEnumNullable] = Field(None, alias='status')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
