# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from quivr_python_sdk.pydantic.api_brain_definition_entity_output_nullable import ApiBrainDefinitionEntityOutputNullable
from quivr_python_sdk.pydantic.brain_type import BrainType

class PublicBrain(BaseModel):
    id: str = Field(alias='id')

    name: str = Field(alias='name')

    last_update: str = Field(alias='last_update')

    brain_type: BrainType = Field(alias='brain_type')

    description: typing.Optional[typing.Optional[str]] = Field(None, alias='description')

    number_of_subscribers: typing.Optional[int] = Field(None, alias='number_of_subscribers')

    brain_definition: typing.Optional[ApiBrainDefinitionEntityOutputNullable] = Field(None, alias='brain_definition')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
