# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from quivr_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    BRAINS_PUBLIC = "/brains/public"
    BRAINS_BRAIN_ID_SECRETSVALUES = "/brains/{brain_id}/secrets-values"
    BRAINS_BRAIN_ID_DEFAULT = "/brains/{brain_id}/default"
    BRAINS_BRAIN_ID_DOCUMENTS = "/brains/{brain_id}/documents"
    CHAT_HEALTHZ = "/chat/healthz"
    CHAT = "/chat"
    CHAT_CHAT_ID = "/chat/{chat_id}"
    CHAT_CHAT_ID_METADATA = "/chat/{chat_id}/metadata"
    CHAT_CHAT_ID_MESSAGE_ID = "/chat/{chat_id}/{message_id}"
    CHAT_CHAT_ID_QUESTION = "/chat/{chat_id}/question"
    CHAT_CHAT_ID_QUESTION_STREAM = "/chat/{chat_id}/question/stream"
    CHAT_CHAT_ID_HISTORY = "/chat/{chat_id}/history"
    CHAT_CHAT_ID_QUESTION_ANSWER = "/chat/{chat_id}/question/answer"
    CRAWL_HEALTHZ = "/crawl/healthz"
    CRAWL = "/crawl"
    ONBOARDING = "/onboarding"
    _ = "/"
    HEALTHZ = "/healthz"
    UPLOAD_HEALTHZ = "/upload/healthz"
    UPLOAD = "/upload"
    USER = "/user"
    USER_IDENTITY = "/user/identity"
    APIKEY = "/api-key"
    APIKEY_KEY_ID = "/api-key/{key_id}"
    APIKEYS = "/api-keys"
    BRAINS_BRAIN_ID_SUBSCRIPTION = "/brains/{brain_id}/subscription"
    BRAINS_BRAIN_ID_USERS = "/brains/{brain_id}/users"
    BRAINS_BRAIN_ID_SUBSCRIPTION_ACCEPT = "/brains/{brain_id}/subscription/accept"
    BRAINS_BRAIN_ID_SUBSCRIPTION_DECLINE = "/brains/{brain_id}/subscription/decline"
    BRAINS_BRAIN_ID_SUBSCRIBE = "/brains/{brain_id}/subscribe"
    BRAINS_BRAIN_ID_UNSUBSCRIBE = "/brains/{brain_id}/unsubscribe"
    PROMPTS = "/prompts"
    PROMPTS_PROMPT_ID = "/prompts/{prompt_id}"
    NOTIFICATIONS_CHAT_ID = "/notifications/{chat_id}"
    KNOWLEDGE = "/knowledge"
    KNOWLEDGE_KNOWLEDGE_ID = "/knowledge/{knowledge_id}"
    KNOWLEDGE_KNOWLEDGE_ID_SIGNED_DOWNLOAD_URL = "/knowledge/{knowledge_id}/signed_download_url"
    CONTACT = "/contact"
    BRAINS_INTEGRATIONS = "/brains/integrations"
    BRAINS = "/brains"
    BRAINS_DEFAULT = "/brains/default"
    BRAINS_BRAIN_ID = "/brains/{brain_id}"
