# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import quivr_python_sdk
from quivr_python_sdk.model.prompt_get_all_public_prompts_response import PromptGetAllPublicPromptsResponse
from quivr_python_sdk import configuration


class TestPromptGetAllPublicPromptsResponse(unittest.TestCase):
    """PromptGetAllPublicPromptsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
