# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import quivr_python_sdk
from quivr_python_sdk.model.onboarding_updatable_properties import OnboardingUpdatableProperties
from quivr_python_sdk import configuration


class TestOnboardingUpdatableProperties(unittest.TestCase):
    """OnboardingUpdatableProperties unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
