# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import quivr_python_sdk
from quivr_python_sdk.model.chat_item_type import ChatItemType
from quivr_python_sdk import configuration


class TestChatItemType(unittest.TestCase):
    """ChatItemType unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
