# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import quivr_python_sdk
from quivr_python_sdk.model.question_and_answer import QuestionAndAnswer
from quivr_python_sdk import configuration


class TestQuestionAndAnswer(unittest.TestCase):
    """QuestionAndAnswer unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
