# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.api_key.post import CreateNewKey
from quivr_python_sdk.paths.api_key_key_id.delete import DeleteKey
from quivr_python_sdk.paths.api_keys.get import GetList
from quivr_python_sdk.apis.tags.api_key_api_raw import APIKeyApiRaw


class APIKeyApi(
    CreateNewKey,
    DeleteKey,
    GetList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: APIKeyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = APIKeyApiRaw(api_client)
