# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.api_key.post import CreateNewKeyRaw
from quivr_python_sdk.paths.api_key_key_id.delete import DeleteKeyRaw
from quivr_python_sdk.paths.api_keys.get import GetListRaw


class APIKeyApiRaw(
    CreateNewKeyRaw,
    DeleteKeyRaw,
    GetListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
