# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.brains_brain_id_subscription_accept.post import AcceptInvitationRaw
from quivr_python_sdk.paths.brains.post import CreateNewBrainRaw
from quivr_python_sdk.paths.brains_brain_id_subscription_decline.post import DeclineInvitationRaw
from quivr_python_sdk.paths.brains.get import GetAllForUserRaw
from quivr_python_sdk.paths.brains_public.get import GetAllPublicRaw
from quivr_python_sdk.paths.brains_brain_id.get import GetByIdRaw
from quivr_python_sdk.paths.brains_default.get import GetDefaultBrainRaw
from quivr_python_sdk.paths.brains_integrations.get import GetDescriptionRaw
from quivr_python_sdk.paths.brains_brain_id_documents.post import GetQuestionContextRaw
from quivr_python_sdk.paths.brains_brain_id_users.get import GetUsersRaw
from quivr_python_sdk.paths.brains_brain_id_subscription.delete import RemoveUserSubscriptionRaw
from quivr_python_sdk.paths.brains_brain_id_default.post import SetDefaultRaw
from quivr_python_sdk.paths.brains_brain_id.put import UpdateConfigurationRaw
from quivr_python_sdk.paths.brains_brain_id_secrets_values.put import UpdateSecretsValuesRaw
from quivr_python_sdk.paths.brains_brain_id_subscription.put import UpdateSubscriptionRaw


class BrainApiRaw(
    AcceptInvitationRaw,
    CreateNewBrainRaw,
    DeclineInvitationRaw,
    GetAllForUserRaw,
    GetAllPublicRaw,
    GetByIdRaw,
    GetDefaultBrainRaw,
    GetDescriptionRaw,
    GetQuestionContextRaw,
    GetUsersRaw,
    RemoveUserSubscriptionRaw,
    SetDefaultRaw,
    UpdateConfigurationRaw,
    UpdateSecretsValuesRaw,
    UpdateSubscriptionRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
