# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.brains_brain_id_subscription.get import GetUserInvitation
from quivr_python_sdk.paths.brains_brain_id_subscription.post import InviteUsersToBrain
from quivr_python_sdk.apis.tags.brain_subscription_api_raw import BrainSubscriptionApiRaw


class BrainSubscriptionApi(
    GetUserInvitation,
    InviteUsersToBrain,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BrainSubscriptionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BrainSubscriptionApiRaw(api_client)
