# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.brains_brain_id_subscription.get import GetUserInvitationRaw
from quivr_python_sdk.paths.brains_brain_id_subscription.post import InviteUsersToBrainRaw


class BrainSubscriptionApiRaw(
    GetUserInvitationRaw,
    InviteUsersToBrainRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
