# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.brains_brain_id_subscription_accept.post import AcceptInvitation
from quivr_python_sdk.paths.brains.post import CreateNewBrain
from quivr_python_sdk.paths.brains_brain_id_subscription_decline.post import DeclineInvitation
from quivr_python_sdk.paths.brains.get import GetAllForUser
from quivr_python_sdk.paths.brains_public.get import GetAllPublic
from quivr_python_sdk.paths.brains_brain_id.get import GetById
from quivr_python_sdk.paths.brains_default.get import GetDefaultBrain
from quivr_python_sdk.paths.brains_integrations.get import GetDescription
from quivr_python_sdk.paths.brains_brain_id_documents.post import GetQuestionContext
from quivr_python_sdk.paths.brains_brain_id_users.get import GetUsers
from quivr_python_sdk.paths.brains_brain_id_subscription.delete import RemoveUserSubscription
from quivr_python_sdk.paths.brains_brain_id_default.post import SetDefault
from quivr_python_sdk.paths.brains_brain_id.put import UpdateConfiguration
from quivr_python_sdk.paths.brains_brain_id_secrets_values.put import UpdateSecretsValues
from quivr_python_sdk.paths.brains_brain_id_subscription.put import UpdateSubscription
from quivr_python_sdk.apis.tags.brain_api_raw import BrainApiRaw


class BrainApi(
    AcceptInvitation,
    CreateNewBrain,
    DeclineInvitation,
    GetAllForUser,
    GetAllPublic,
    GetById,
    GetDefaultBrain,
    GetDescription,
    GetQuestionContext,
    GetUsers,
    RemoveUserSubscription,
    SetDefault,
    UpdateConfiguration,
    UpdateSecretsValues,
    UpdateSubscription,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BrainApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BrainApiRaw(api_client)
