# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.chat_chat_id_question_answer.post import AddQuestionAndAnswerRaw
from quivr_python_sdk.paths.chat.post import CreateHandlerRaw
from quivr_python_sdk.paths.chat_chat_id_question_stream.post import CreateStreamQuestionHandlerRaw
from quivr_python_sdk.paths.chat_chat_id.delete import DeleteChatByIdRaw
from quivr_python_sdk.paths.chat.get import GetAllChatsRaw
from quivr_python_sdk.paths.chat_chat_id_history.get import GetHistoryRaw
from quivr_python_sdk.paths.chat_chat_id_question.post import HandleQuestionRaw
from quivr_python_sdk.paths.chat_chat_id_message_id.put import UpdateMessageRaw
from quivr_python_sdk.paths.chat_chat_id_metadata.put import UpdateMetadataHandlerRaw


class ChatApiRaw(
    AddQuestionAndAnswerRaw,
    CreateHandlerRaw,
    CreateStreamQuestionHandlerRaw,
    DeleteChatByIdRaw,
    GetAllChatsRaw,
    GetHistoryRaw,
    HandleQuestionRaw,
    UpdateMessageRaw,
    UpdateMetadataHandlerRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
