# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.contact.post import CreateNewContact
from quivr_python_sdk.apis.tags.contact_api_raw import ContactApiRaw


class ContactApi(
    CreateNewContact,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ContactApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ContactApiRaw(api_client)
