# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.crawl.post import WebsiteDataProcessor
from quivr_python_sdk.apis.tags.crawl_api_raw import CrawlApiRaw


class CrawlApi(
    WebsiteDataProcessor,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CrawlApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CrawlApiRaw(api_client)
