# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.chat_healthz.get import CheckStatusRaw
from quivr_python_sdk.paths.crawl_healthz.get import CheckStatus0Raw
from quivr_python_sdk.paths.healthz.get import CheckStatus1Raw
from quivr_python_sdk.paths.upload_healthz.get import CheckStatus2Raw


class HealthApiRaw(
    CheckStatusRaw,
    CheckStatus0Raw,
    CheckStatus1Raw,
    CheckStatus2Raw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
