# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.chat_healthz.get import CheckStatus
from quivr_python_sdk.paths.crawl_healthz.get import CheckStatus0
from quivr_python_sdk.paths.healthz.get import CheckStatus1
from quivr_python_sdk.paths.upload_healthz.get import CheckStatus2
from quivr_python_sdk.apis.tags.health_api_raw import HealthApiRaw


class HealthApi(
    CheckStatus,
    CheckStatus0,
    CheckStatus1,
    CheckStatus2,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HealthApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HealthApiRaw(api_client)
