# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.notifications_chat_id.get import GetByChatId
from quivr_python_sdk.apis.tags.notification_api_raw import NotificationApiRaw


class NotificationApi(
    GetByChatId,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: NotificationApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = NotificationApiRaw(api_client)
