# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.onboarding.get import GetUserInfoRaw
from quivr_python_sdk.paths.onboarding.put import UpdateUserOnboardingRaw


class OnboardingApiRaw(
    GetUserInfoRaw,
    UpdateUserOnboardingRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
