# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.onboarding.get import GetUserInfo
from quivr_python_sdk.paths.onboarding.put import UpdateUserOnboarding
from quivr_python_sdk.apis.tags.onboarding_api_raw import OnboardingApiRaw


class OnboardingApi(
    GetUserInfo,
    UpdateUserOnboarding,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OnboardingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OnboardingApiRaw(api_client)
