# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.prompts.post import CreatePromptById
from quivr_python_sdk.paths.prompts.get import GetAllPublicPrompts
from quivr_python_sdk.paths.prompts_prompt_id.get import GetById
from quivr_python_sdk.paths.prompts_prompt_id.put import UpdateById
from quivr_python_sdk.apis.tags.prompt_api_raw import PromptApiRaw


class PromptApi(
    CreatePromptById,
    GetAllPublicPrompts,
    GetById,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PromptApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PromptApiRaw(api_client)
