# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.prompts.post import CreatePromptByIdRaw
from quivr_python_sdk.paths.prompts.get import GetAllPublicPromptsRaw
from quivr_python_sdk.paths.prompts_prompt_id.get import GetByIdRaw
from quivr_python_sdk.paths.prompts_prompt_id.put import UpdateByIdRaw


class PromptApiRaw(
    CreatePromptByIdRaw,
    GetAllPublicPromptsRaw,
    GetByIdRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
