# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.root.get import StatusCheck
from quivr_python_sdk.apis.tags.root_api_raw import RootApiRaw


class RootApi(
    StatusCheck,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RootApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RootApiRaw(api_client)
