# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.brains_brain_id_subscribe.post import BrainHandler
from quivr_python_sdk.paths.brains_brain_id_unsubscribe.post import UnregisterHandler
from quivr_python_sdk.apis.tags.subscription_api_raw import SubscriptionApiRaw


class SubscriptionApi(
    BrainHandler,
    UnregisterHandler,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SubscriptionApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SubscriptionApiRaw(api_client)
