# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.brains_brain_id_subscribe.post import BrainHandlerRaw
from quivr_python_sdk.paths.brains_brain_id_unsubscribe.post import UnregisterHandlerRaw


class SubscriptionApiRaw(
    BrainHandlerRaw,
    UnregisterHandlerRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
