# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.upload.post import FilePost
from quivr_python_sdk.apis.tags.upload_api_raw import UploadApiRaw


class UploadApi(
    FilePost,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UploadApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UploadApiRaw(api_client)
