# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.user_identity.get import GetIdentityRouteRaw
from quivr_python_sdk.paths.user.get import GetUserInformationRaw
from quivr_python_sdk.paths.user_identity.put import UpdateIdentityRouteRaw


class UserApiRaw(
    GetIdentityRouteRaw,
    GetUserInformationRaw,
    UpdateIdentityRouteRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
