# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from quivr_python_sdk.paths.user_identity.get import GetIdentityRoute
from quivr_python_sdk.paths.user.get import GetUserInformation
from quivr_python_sdk.paths.user_identity.put import UpdateIdentityRoute
from quivr_python_sdk.apis.tags.user_api_raw import UserApiRaw


class UserApi(
    GetIdentityRoute,
    GetUserInformation,
    UpdateIdentityRoute,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserApiRaw(api_client)
