# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.api_brain_definition_schema_property import ApiBrainDefinitionSchemaProperty
from quivr_python_sdk.type.api_brain_definition_schema_required import ApiBrainDefinitionSchemaRequired

class RequiredApiBrainDefinitionSchema(TypedDict):
    pass

class OptionalApiBrainDefinitionSchema(TypedDict, total=False):
    properties: typing.List[ApiBrainDefinitionSchemaProperty]

    required: ApiBrainDefinitionSchemaRequired

class ApiBrainDefinitionSchema(RequiredApiBrainDefinitionSchema, OptionalApiBrainDefinitionSchema):
    pass
