# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredApiKey(TypedDict):
    api_key: str

    key_id: str

    days: int

    only_chat: bool

    name: str

    creation_time: str

    is_active: bool

class OptionalApiKey(TypedDict, total=False):
    pass

class ApiKey(RequiredApiKey, OptionalApiKey):
    pass
