# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredApiKeyInfo(TypedDict):
    key_id: str

    creation_time: str

class OptionalApiKeyInfo(TypedDict, total=False):
    pass

class ApiKeyInfo(RequiredApiKeyInfo, OptionalApiKeyInfo):
    pass
