# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.api_brain_definition_entity_input_nullable import ApiBrainDefinitionEntityInputNullable
from quivr_python_sdk.type.brain_integration_update_settings_nullable import BrainIntegrationUpdateSettingsNullable
from quivr_python_sdk.type.brain_updatable_properties_connected_brains_ids import BrainUpdatablePropertiesConnectedBrainsIds

class RequiredBrainUpdatableProperties(TypedDict):
    pass

class OptionalBrainUpdatableProperties(TypedDict, total=False):
    description: typing.Optional[str]

    name: typing.Optional[str]

    temperature: typing.Optional[typing.Union[int, float]]

    model: typing.Optional[str]

    max_tokens: typing.Optional[int]

    status: typing.Optional[str]

    prompt_id: typing.Optional[str]

    brain_definition: typing.Optional[ApiBrainDefinitionEntityInputNullable]

    connected_brains_ids: typing.Optional[BrainUpdatablePropertiesConnectedBrainsIds]

    integration: typing.Optional[BrainIntegrationUpdateSettingsNullable]

class BrainUpdatableProperties(RequiredBrainUpdatableProperties, OptionalBrainUpdatableProperties):
    pass
