# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredBrainIntegrationSettings(TypedDict):
    integration_id: str

    settings: typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]

class OptionalBrainIntegrationSettings(TypedDict, total=False):
    pass

class BrainIntegrationSettings(RequiredBrainIntegrationSettings, OptionalBrainIntegrationSettings):
    pass
