# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.chat_item_type import ChatItemType
from quivr_python_sdk.type.get_chat_history_output import GetChatHistoryOutput
from quivr_python_sdk.type.notification import Notification

class RequiredChatItem(TypedDict):
    item_type: ChatItemType

    body: typing.Union[GetChatHistoryOutput, Notification]

class OptionalChatItem(TypedDict, total=False):
    pass

class ChatItem(RequiredChatItem, OptionalChatItem):
    pass
