# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredChatNullable(TypedDict):
    chat_id: str

    user_id: str

    creation_time: str

    chat_name: str

class OptionalChatNullable(TypedDict, total=False):
    pass

class ChatNullable(RequiredChatNullable, OptionalChatNullable):
    pass
