# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContactMessage(TypedDict):
    customer_email: str

    content: str

class OptionalContactMessage(TypedDict, total=False):
    pass

class ContactMessage(RequiredContactMessage, OptionalContactMessage):
    pass
