# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.brain_integration_settings_nullable import BrainIntegrationSettingsNullable
from quivr_python_sdk.type.brain_type_nullable import BrainTypeNullable
from quivr_python_sdk.type.create_api_brain_definition_nullable import CreateApiBrainDefinitionNullable
from quivr_python_sdk.type.create_brain_properties_connected_brains_ids import CreateBrainPropertiesConnectedBrainsIds

class RequiredCreateBrainProperties(TypedDict):
    pass

class OptionalCreateBrainProperties(TypedDict, total=False):
    description: str

    name: typing.Optional[str]

    status: typing.Optional[str]

    model: typing.Optional[str]

    temperature: typing.Optional[typing.Union[int, float]]

    max_tokens: typing.Optional[int]

    prompt_id: typing.Optional[str]

    brain_type: typing.Optional[BrainTypeNullable]

    brain_definition: typing.Optional[CreateApiBrainDefinitionNullable]

    brain_secrets_values: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]

    connected_brains_ids: typing.Optional[CreateBrainPropertiesConnectedBrainsIds]

    integration: typing.Optional[BrainIntegrationSettingsNullable]

class CreateBrainProperties(RequiredCreateBrainProperties, OptionalCreateBrainProperties):
    pass
