# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGetChatHistoryOutput(TypedDict):
    chat_id: str

    message_id: typing.Union[str, str]

    user_message: str

    assistant: str

class OptionalGetChatHistoryOutput(TypedDict, total=False):
    message_time: typing.Optional[str]

    prompt_title: typing.Optional[str]

    brain_name: typing.Optional[str]

    brain_id: typing.Optional[str]

    metadata: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]

    thumbs: typing.Optional[bool]

class GetChatHistoryOutput(RequiredGetChatHistoryOutput, OptionalGetChatHistoryOutput):
    pass
