# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.validation_error import ValidationError

class RequiredHTTPValidationError(TypedDict):
    pass

class OptionalHTTPValidationError(TypedDict, total=False):
    detail: typing.List[ValidationError]

class HTTPValidationError(RequiredHTTPValidationError, OptionalHTTPValidationError):
    pass
