# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.notifications_status_enum import NotificationsStatusEnum

class RequiredNotification(TypedDict):
    id: str

    datetime: str

    action: str

    status: NotificationsStatusEnum

class OptionalNotification(TypedDict, total=False):
    chat_id: typing.Optional[str]

    message: typing.Optional[str]

class Notification(RequiredNotification, OptionalNotification):
    pass
