# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredOnboardingUpdatableProperties(TypedDict):
    pass

class OptionalOnboardingUpdatableProperties(TypedDict, total=False):
    onboarding_a: typing.Optional[bool]

    onboarding_b1: typing.Optional[bool]

    onboarding_b2: typing.Optional[bool]

    onboarding_b3: typing.Optional[bool]

class OnboardingUpdatableProperties(RequiredOnboardingUpdatableProperties, OptionalOnboardingUpdatableProperties):
    pass
