# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.api_brain_definition_entity_output_nullable import ApiBrainDefinitionEntityOutputNullable
from quivr_python_sdk.type.brain_type import BrainType

class RequiredPublicBrain(TypedDict):
    id: str

    name: str

    last_update: str

    brain_type: BrainType

class OptionalPublicBrain(TypedDict, total=False):
    description: typing.Optional[str]

    number_of_subscribers: int

    brain_definition: typing.Optional[ApiBrainDefinitionEntityOutputNullable]

class PublicBrain(RequiredPublicBrain, OptionalPublicBrain):
    pass
