# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUserIdentity(TypedDict):
    id: str

class OptionalUserIdentity(TypedDict, total=False):
    email: typing.Optional[str]

    username: typing.Optional[str]

    company: typing.Optional[str]

    onboarded: typing.Optional[bool]

    company_size: typing.Optional[str]

    usage_purpose: typing.Optional[str]

class UserIdentity(RequiredUserIdentity, OptionalUserIdentity):
    pass
