# coding: utf-8

"""
    FastAPI

    Open-source RAG Framework

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from quivr_python_sdk.type.validation_error_loc import ValidationErrorLoc

class RequiredValidationError(TypedDict):
    loc: ValidationErrorLoc

    msg: str

    type: str

class OptionalValidationError(TypedDict, total=False):
    pass

class ValidationError(RequiredValidationError, OptionalValidationError):
    pass
